################################# Default configuration ###################
# provide your domain here
baseURL = "https://wasserkreislauf.github.io/"
# theme
theme = "dot"
# site title
title = "Wasserkreislauf"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]


# customize color
primary_color = "#52BE80"
body_color = "#f9f9f9"
text_color = ""
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################



################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

[Languages.en.params]
# logo is for all page
logo = "images/Logo_Fernuni_en.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/FernuniLogoWhite_en.png"
# when logo is empty, it will shown your site title


# banner
[Languages.en.params.banner]
title = "The water cycle"
subtitle = "The use of virtual reality in science teaching"
bg_image = "images/grass.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = ""

# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "home"
url = "/"
weight = 1


[[Languages.en.menu.main]]
name = "contact"
url = "contact"
weight = 2

# Dropdown menu
[[Languages.en.menu.main]]
weight = 3
name = "topics"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "Teacher"
  url = "teacher"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "Projects"
  url = "project"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "Team"
  url = "team"
  weight = 3



################################### German Language ######################
[Languages.de]
languageName = "De"
languageCode = "de-de"
weight = 2
copyright = "Die Hugo-Dokumente sind urheberrechtlich geschützt © [gethugothemes](https://gethugothemes.com/) 2020."

[Languages.de.params]
# logo is for all page
logo = "images/Logo_Fernuni_de.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/FernuniLogoWhite_de.png"
# when logo is empty, it will shown your site title


# banner

[Languages.de.params.banner]
title = "Der Wasserkreislauf"
subtitle = "Der Nutzen von Virtueller Realität im Naturwissenschaftlichen Unterricht"
bg_image = "images/grass.jpg"
placeholder = "remove search bar"

# call to action
[Languages.de.params.cta]
enable = true
title = "Sie haben keine Antwort auf Ihre Frage gefunden?"
content = ""

# call to action button
[Languages.de.params.cta.button]
enable = true
label = "Kontaktiern Sie uns"
link = "contact"

################## german navigation #################
[[Languages.de.menu.main]]
name = "startseite"
url = "/"
weight = 1

[[Languages.de.menu.main]]
name = "Kontakt"
url = "contact"
weight = 2

# Dropdown menu
[[Languages.de.menu.main]]
weight = 3
name = "themen"
hasChildren = true

  [[Languages.de.menu.main]]
  parent = "themen"
  name = "Lehrpersonen"
  url = "teacher"
  weight = 1

  [[Languages.de.menu.main]]
  parent = "themen"
  name = "Projekt"
  url = "project"
  weight = 2

  [[Languages.de.menu.main]]
  parent = "themen"
  name = "Team"
  url = "team"
  weight = 3